### ISSUE TITLE
Does not compile php version 7.4 since gd options changed

### ISSUE THREAD

**Issue by frunika** [getgrav/docker-grav#25]
https://github.com/getgrav/docker-grav/blob/1858f38e52a4e3f9fceb0743a6f36b4f97ccfb2b/Dockerfile#L27

Need's to be changed to:
`&& docker-php-ext-configure gd --with-freetype --with-jpeg \`

 (ref to https://github.com/docker-library/php/issues/912)

**Comment by mahagr** [comment]
Yup, I can confirm this as I had to figure it out myself.

**Comment by rhukster** [comment]
Fixed
