### ISSUE TITLE
grav-admin-${GRAV_VERSION}.zip is "Not found"

### ISSUE THREAD

**Issue by felixzwettler** [getgrav/docker-grav#42]
Building the Dockerfile gives me an error when it tries to execute lines 59-62 
```
RUN curl -o grav-admin.zip -SL https://getgrav.org/download/core/grav-admin/${GRAV_VERSION} && \
    unzip grav-admin.zip && \
    mv -T /var/www/grav-admin /var/www/html && \
    rm grav-admin.zip

```
GRAV_VERSION is set to `latest` and points to `https://github.com/getgrav/grav/releases/download/1.7.11/grav-admin-v1.7.11.zip`
which does not exist. The latest release as of today (2021-04-15) should point to `https://github.com/getgrav/grav/releases/download/1.7.10/grav-admin-v1.7.10.zip`

**Comment by mahagr** [comment]
Should be fixed by now.
