### ISSUE TITLE
Git workflow

### ISSUE THREAD

**Issue by evidence-sharenet** [getgrav/docker-grav#51]
Good day.

Can someone assist me with this issue?

I have just started using the Grav CMS and I'm also quite a newbie with Docker. I managed to set up everything on my local and have even managed to create some themes and plugins. 

I'm now having challenges on how to create a git workflow that would enable me to save my work including the custom themes and plugins.

My question is what is the BEST WAY to have a local dev setup which enables me commit and push my work to a remote repo?

**Comment by mahagr** [comment]
https://getgrav.org/blog/git-sync-plugin
