### ISSUE TITLE
Runtime Exception

### ISSUE THREAD

**Issue by corentincharron** [getgrav/docker-grav#9]
Hello,

I'm using docker-compose as everything on my production server is managed by a nginx reverse proxy.

I'm not sure I understood well the installation instructions though:
I downloaded the latest [Grav + Admin](https://getgrav.org/download/core/grav-admin/latest) and unarchived it to **/srv/doc-user**

Here is the Grav bit of my docker-compose.yml:
```
doc-user:
    image: 'grav:latest'
    container_name: doc-user
    depends_on:
      - proxy
    volumes:
      - /srv/doc-user/:/var/www/html/:cached
```

I get the following error:
```
Fatal error: Uncaught RuntimeException: Creating directory '/var/www/html/cache/compiled/files' failed on error in /var/www/html/vendor/rockettheme/toolbox/File/src/File.php:423 Stack trace: #0 /var/www/html/vendor/rockettheme/toolbox/File/src/File.php(191): RocketTheme\Toolbox\File\File->mkdir('/var/www/html/c...') #1 /var/www/html/vendor/rockettheme/toolbox/File/src/File.php(319): RocketTheme\Toolbox\File\File->lock() #2 /var/www/html/vendor/rockettheme/toolbox/File/src/PhpFile.php(31): RocketTheme\Toolbox\File\File->save(Array) #3 /var/www/html/system/src/Grav/Common/File/CompiledFile.php(64): RocketTheme\Toolbox\File\PhpFile->save(Array) #4 /var/www/html/system/src/Grav/Common/Config/Setup.php(181): Grav\Common\File\CompiledYamlFile->content() #5 /var/www/html/system/src/Grav/Common/Processors/SiteSetupProcessor.php(18): Grav\Common\Config\Setup->init() #6 /var/www/html/system/src/Grav/Common/Grav.php(131): Grav\Common\Processors\SiteSetupProcessor->process() #7 /var/www/html/system/src/Grav/Common/Grav.php(370): Gra in /var/www/html/system/src/Grav/Common/File/CompiledFile.php on line 80
```

Any idea about what I'm doing wrong?

**Comment by Braintelligence** [comment]
You have to `chown -R 33:33 /srv/doc-user`

**Comment by viktor-c** [comment]
As pointed by @Braintelligence you can change the ownership of the folder where you installed grav. For this to work your user has to be part of the `www-data` group. This group has id `33`, which appears in this command `chown -R 33:33 /srv/doc-user`

My workaround was like follows:
1. Go to the Terminal/Konsole in Linux
2. get the id of your running user. `id` My output looks like this: id 
`uid=1000(viktor) gid=1000(viktor) Groups=1000(viktor),...,130(docker)`
we will use 1000 as UID and GUID in the following code. Replace with your ID
3. In your Dockerfile change following lines:
```
RUN chown www-data:www-data /var/www
USER www-data
```
with these
```
ARG UID=1000
ARG GUID=1000
RUN chown www-data:www-data /var/www
RUN useradd -u $UID newuser
RUN usermod -a -G newuser www-data
USER www-data
```
4. Build and run your grav container 

Like this you will add a new user in the grav container. This user has the same ID as your localuser has. Then it will add the group of this user to www-data. As such www-data will have access to your local folder. And so will you.
:)
